# Workflow for deploying both FoodApp (Web App) and API project

name: Build and deploy ASP.Net Core apps to Azure Web Apps - FoodApp & API

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up .NET Core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '8.0.x'
          include-prerelease: true

      - name: Build with dotnet
        run: dotnet build --configuration Release

      - name: Run Tests 
        run: |
            echo "Running unit tests..."
            dotnet test --configuration Release --no-build --logger "console;verbosity=detailed" 
            
      - name: dotnet publish FoodApp
        run: dotnet publish FoodApp/FoodApp.csproj -c Release -o ${{env.DOTNET_ROOT}}/FoodApp

      - name: dotnet publish API
        run: dotnet publish API/API.csproj -c Release -o ${{env.DOTNET_ROOT}}/API  

      - name: dotnet publish Infrastructure
        run: dotnet publish Infrastructure/Infrastructure.csproj -c Release -o ${{env.DOTNET_ROOT}}/Infrastructure

      - name: Upload artifact for FoodApp deployment
        uses: actions/upload-artifact@v3
        with:
          name: foodappsr 
          path: ${{env.DOTNET_ROOT}}/FoodApp

      - name: Upload artifact for API deployment
        uses: actions/upload-artifact@v3
        with:
          name: api  
          path: ${{env.DOTNET_ROOT}}/API

      - name: Upload artifact for Infrastructure deployment
        uses: actions/upload-artifact@v3
        with:
          name: infrastructure  
          path: ./Infrastructure/**

      - name: Controleer inhoud van Infrastructure artifact
        run: |
          echo "Inhoud van Infrastructure:"
          ls -R ./InfrastructureArtifact


  deploy:
    runs-on: windows-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-foodapp.outputs.webapp-url }}  
    permissions:
      id-token: write 

    steps:
      - name: Download artifact from build job (FoodApp)
        uses: actions/download-artifact@v3
        with:
          name: foodappsr  
          path: ./FoodAppArtifact

      - name: Download artifact from build job (API)
        uses: actions/download-artifact@v3
        with:
          name: api 
          path: ./APIArtifact

      - name: Download artifact from build job (Infrastructure)
        uses: actions/download-artifact@v3
        with:
          name: infrastructure 
          path: ./InfrastructureArtifact

      - name: List Files in FoodAppArtifact
        run: ls ./FoodAppArtifact

      - name: List Files in APIArtifact
        run: ls ./APIArtifact

      - name: List Files in InfrastructureArtifact
        run: ls ./InfrastructureArtifact

      - name: Current Path/Location
        run: pwd

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_D79BCCD855384EE9B63C5D16E44B6316 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_37EA4F686BA347B397AE3C01F10C7D40 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_F68EDC77859946889E817C791748FEB2 }}

      - name: Install dotnet-ef tool
        run: dotnet tool install --global dotnet-ef

      - name: Add dotnet tools to PATH
        run: echo "${{ runner.tool_cache }}/.dotnet/tools" >> $GITHUB_PATH

      # Nieuwe stap om migraties voor FoodAppDb toe te passen
      - name: Apply migrations for FoodAppDb
        run: dotnet ef database update --project D:\a\SSWF-FoodApp\SSWF-FoodApp\InfrastructureArtifact\Infrastructure\Infrastructure.csproj --context FoodAppDbContext
        env:
          AZURE_SQL_CONNECTIONSTRINGFOODAPPDB: ${{ secrets.AZURE_CONNECTIONSTRING_FOODAPPDB }}

      # Nieuwe stap om migraties voor FoodAppIdentityDb toe te passen
      - name: Apply migrations for FoodAppIdentityDb
        run: dotnet ef database update --project Infrastructure.csproj --context FoodAppIdentityDbContext
        env:
          AZURE_SQL_CONNECTIONSTRINGIDENTITYDB: ${{ secrets.AZURE_CONNECTIONSTRING_IDENTITYDB }}

      - name: Deploy FoodApp to Azure Web App
        id: deploy-to-foodapp
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'avansfoodappsr' 
          slot-name: 'Production'
          package: ./FoodAppArtifact  

      - name: Deploy API to Azure Web App
        id: deploy-to-api
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'avansfoodappsrapi'  
          slot-name: 'Production'
          package: ./APIArtifact
