# Workflow for deploying both FoodApp (Web App) and API project

name: Build and deploy ASP.Net Core apps to Azure Web Apps - FoodApp & API

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up .NET Core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '8.0.x'
          include-prerelease: true

      - name: Build with dotnet
        run: dotnet build --configuration Release

      - name: Run Tests 
        run: |
            echo "Running unit tests..."
            dotnet test --configuration Release --no-build --logger "console;verbosity=detailed" 

        # Maak de tool-manifest en installeer dotnet-ef
      - name: Create .NET Tool Manifest
        run: dotnet new tool-manifest --output .

      - name: Install dotnet-ef tool
        run: dotnet tool install dotnet-ef

      # Migration bundle voor FoodAppDB
      - name: Bundle Migrations for FoodAppDB
        run: dotnet ef migrations bundle --self-contained -s $(Build.SourcesDirectory)/FoodApp -p $(Build.SourcesDirectory)/FoodApp -c FoodAppDbContext -o $(Build.SourcesDirectory)/FoodApp/migration_bundle_foodappdb/bundle

      # Migration bundle voor IdentityDB
      - name: Bundle Migrations for IdentityDB
        run: dotnet ef migrations bundle --self-contained -s $(Build.SourcesDirectory)/FoodApp -p $(Build.SourcesDirectory)/FoodApp -c IdentityDbContext -o $(Build.SourcesDirectory)/FoodApp/migration_bundle_identitydb/bundle

      # Publish beide migration bundles als artifacts
      - name: Publish Migrations Bundle Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: EfMigrationsBundle_FoodAppDB
          path: $(Build.SourcesDirectory)/FoodApp/migration_bundle_foodappdb

      - name: Publish Identity Migrations Bundle Artifact
        uses: actions/upload-artifact@v3
        with:
          name: EfMigrationsBundle_IdentityDB
          path: $(Build.SourcesDirectory)/FoodApp/migration_bundle_identitydb

      - name: dotnet publish FoodApp
        run: dotnet publish FoodApp/FoodApp.csproj -c Release -o ${{env.DOTNET_ROOT}}/FoodApp

      - name: dotnet publish API
        run: dotnet publish API/API.csproj -c Release -o ${{env.DOTNET_ROOT}}/API  

      - name: Upload artifact for FoodApp deployment
        uses: actions/upload-artifact@v3
        with:
          name: foodappsr 
          path: ${{env.DOTNET_ROOT}}/FoodApp

      - name: Upload artifact for API deployment
        uses: actions/upload-artifact@v3
        with:
          name: api  
          path: ${{env.DOTNET_ROOT}}/API

  deploy:
    runs-on: windows-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-foodapp.outputs.webapp-url }}  
    permissions:
      id-token: write 

    steps:
      - name: Download artifact from build job (FoodApp)
        uses: actions/download-artifact@v3
        with:
          name: foodappsr  
          path: ./FoodAppArtifact

      - name: Download artifact from build job (API)
        uses: actions/download-artifact@v3
        with:
          name: api 
          path: ./APIArtifact

      # Download Migration Bundles for FoodAppDB and IdentityDB
      - name: Download Migration Bundle for FoodAppDB
        uses: actions/download-artifact@v3
        with:
          name: EfMigrationsBundle_FoodAppDB
          path: ./FoodAppMigrationBundle

      - name: Download Migration Bundle for IdentityDB
        uses: actions/download-artifact@v3
        with:
          name: EfMigrationsBundle_IdentityDB
          path: ./IdentityMigrationBundle

      # Voer migraties uit voor FoodAppDB
      - name: Apply Migrations to FoodAppDB
        run: |
          chmod +x ./FoodAppMigrationBundle/bundle
          ./FoodAppMigrationBundle/bundle --connection="$AZURE_CONNECTIONSTRING_FOODAPPDB"
        env:
          AZURE_CONNECTIONSTRING_FOODAPPDB: ${{ secrets.AZURE_CONNECTIONSTRING_FOODAPPDB }}

      # Voer migraties uit voor IdentityDB
      - name: Apply Migrations to IdentityDB
        run: |
          chmod +x ./IdentityMigrationBundle/bundle
          ./IdentityMigrationBundle/bundle --connection="$AZURE_CONNECTIONSTRING_IDENTITYDB"
        env:
          AZURE_CONNECTIONSTRING_IDENTITYDB: ${{ secrets.AZURE_CONNECTIONSTRING_IDENTITYDB }}

      - name: List Files in FoodAppArtifact
        run: ls ./FoodAppArtifact

      - name: List Files in APIArtifact
        run: ls ./APIArtifact

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_D79BCCD855384EE9B63C5D16E44B6316 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_37EA4F686BA347B397AE3C01F10C7D40 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_F68EDC77859946889E817C791748FEB2 }}

      - name: Deploy FoodApp to Azure Web App
        id: deploy-to-foodapp
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'avansfoodappsr' 
          slot-name: 'Production'
          package: ./FoodAppArtifact  

      - name: Deploy API to Azure Web App
        id: deploy-to-api
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'avansfoodappsrapi'  
          slot-name: 'Production'
          package: ./APIArtifact
